/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IDkimVerifier } from "./IDkimVerifier";
export type { IEmailGuardian } from "./IEmailGuardian";
export type { INS } from "./INS";
export type { INameWrapper } from "./INameWrapper";
export type { IRegistrar } from "./IRegistrar";
export type { IResolver } from "./IResolver";
export type { IReverseRegistrar } from "./IReverseRegistrar";
export type { IVerifier } from "./IVerifier";
