/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IEmailGuardian,
  IEmailGuardianInterface,
} from "../../../src/interfaces/IEmailGuardian";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "server",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "email",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "signature",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "target",
        type: "bytes",
      },
    ],
    name: "validateDKIM",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IEmailGuardian__factory {
  static readonly abi = _abi;
  static createInterface(): IEmailGuardianInterface {
    return new utils.Interface(_abi) as IEmailGuardianInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IEmailGuardian {
    return new Contract(address, _abi, signerOrProvider) as IEmailGuardian;
  }
}
