/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { ZKPassAccount } from "./ZKPassAccount";
export type { ZKPassAccountFactory } from "./ZKPassAccountFactory";
